/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidarRouteImport } from './routes/validar'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as AuthenticatedTrocarSenhaRouteImport } from './routes/_authenticated/trocar-senha'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMeusCursosRouteImport } from './routes/_authenticated/meus-cursos'
import { Route as ApiPublicSetupAdminRouteImport } from './routes/api/public/setup-admin'
import { Route as AuthenticatedAprenderSlugLessonIdRouteImport } from './routes/_authenticated/aprender.$slug.$lessonId'

const ValidarRoute = ValidarRouteImport.update({
  id: '/validar',
  path: '/validar',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CursosRoute,
} as any)
const AuthenticatedTrocarSenhaRoute =
  AuthenticatedTrocarSenhaRouteImport.update({
    id: '/trocar-senha',
    path: '/trocar-senha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusCursosRoute = AuthenticatedMeusCursosRouteImport.update({
  id: '/meus-cursos',
  path: '/meus-cursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSetupAdminRoute = ApiPublicSetupAdminRouteImport.update({
  id: '/api/public/setup-admin',
  path: '/api/public/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAprenderSlugLessonIdRoute =
  AuthenticatedAprenderSlugLessonIdRouteImport.update({
    id: '/aprender/$slug/$lessonId',
    path: '/aprender/$slug/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cursos': typeof CursosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/validar': typeof ValidarRoute
  '/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/aprender/$slug/$lessonId': typeof AuthenticatedAprenderSlugLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cursos': typeof CursosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/validar': typeof ValidarRoute
  '/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/aprender/$slug/$lessonId': typeof AuthenticatedAprenderSlugLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cursos': typeof CursosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/validar': typeof ValidarRoute
  '/_authenticated/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/_authenticated/aprender/$slug/$lessonId': typeof AuthenticatedAprenderSlugLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cursos'
    | '/reset-password'
    | '/validar'
    | '/meus-cursos'
    | '/perfil'
    | '/trocar-senha'
    | '/cursos/$slug'
    | '/api/public/setup-admin'
    | '/aprender/$slug/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cursos'
    | '/reset-password'
    | '/validar'
    | '/meus-cursos'
    | '/perfil'
    | '/trocar-senha'
    | '/cursos/$slug'
    | '/api/public/setup-admin'
    | '/aprender/$slug/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cursos'
    | '/reset-password'
    | '/validar'
    | '/_authenticated/meus-cursos'
    | '/_authenticated/perfil'
    | '/_authenticated/trocar-senha'
    | '/cursos/$slug'
    | '/api/public/setup-admin'
    | '/_authenticated/aprender/$slug/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CursosRoute: typeof CursosRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ValidarRoute: typeof ValidarRoute
  ApiPublicSetupAdminRoute: typeof ApiPublicSetupAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validar': {
      id: '/validar'
      path: '/validar'
      fullPath: '/validar'
      preLoaderRoute: typeof ValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof CursosRoute
    }
    '/_authenticated/trocar-senha': {
      id: '/_authenticated/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof AuthenticatedTrocarSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-cursos': {
      id: '/_authenticated/meus-cursos'
      path: '/meus-cursos'
      fullPath: '/meus-cursos'
      preLoaderRoute: typeof AuthenticatedMeusCursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/setup-admin': {
      id: '/api/public/setup-admin'
      path: '/api/public/setup-admin'
      fullPath: '/api/public/setup-admin'
      preLoaderRoute: typeof ApiPublicSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aprender/$slug/$lessonId': {
      id: '/_authenticated/aprender/$slug/$lessonId'
      path: '/aprender/$slug/$lessonId'
      fullPath: '/aprender/$slug/$lessonId'
      preLoaderRoute: typeof AuthenticatedAprenderSlugLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMeusCursosRoute: typeof AuthenticatedMeusCursosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedTrocarSenhaRoute: typeof AuthenticatedTrocarSenhaRoute
  AuthenticatedAprenderSlugLessonIdRoute: typeof AuthenticatedAprenderSlugLessonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMeusCursosRoute: AuthenticatedMeusCursosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedTrocarSenhaRoute: AuthenticatedTrocarSenhaRoute,
  AuthenticatedAprenderSlugLessonIdRoute:
    AuthenticatedAprenderSlugLessonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CursosRouteChildren {
  CursosSlugRoute: typeof CursosSlugRoute
}

const CursosRouteChildren: CursosRouteChildren = {
  CursosSlugRoute: CursosSlugRoute,
}

const CursosRouteWithChildren =
  CursosRoute._addFileChildren(CursosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CursosRoute: CursosRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ValidarRoute: ValidarRoute,
  ApiPublicSetupAdminRoute: ApiPublicSetupAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
